export interface AnalystReport {
  category: string;
  country: string;
  date: string;
  sector: string;
  summary: string;
  title: string;
  readTime: string;
}

export interface AnalystProfile {
  name: string;
  title: string;
  desk: string;
  location: string;
  badge: string;
  email: string;
  phone: string;
  bio: string;
  focus: string[];
  stats: Array<{ label: string; value: string }>;
  reports: AnalystReport[];
}

function titleFromSlug(slug = '') {
  return slug
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function slugifyAnalystName(name = '') {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const DIRECTORY: Record<string, AnalystProfile> = {
  'ahmed-al-mansour': {
    name: 'Ahmed Al-Mansour',
    title: 'Head of Technology Research',
    desk: 'Technology, Digital Infrastructure',
    location: 'Dubai',
    badge: 'Top Rated Analyst 2024',
    email: 'ahmed.al-mansour@efghermes.com',
    phone: '+20 2 1234 5678',
    bio: 'Ahmed covers technology, fintech, and digital infrastructure across MENA with a focus on monetization, cloud demand, and listed software adoption.',
    focus: ['AI Integration', 'Fintech', 'Digital Infrastructure', 'Platform Economics'],
    stats: [
      { label: 'Reports published', value: '142' },
      { label: 'Covered names', value: '28' },
      { label: 'Markets tracked', value: '6' },
      { label: 'Last published', value: '12 May 2024' },
    ],
    reports: [
      {
        category: 'TECH',
        country: 'Saudi Arabia',
        date: '12 May 2024',
        sector: 'Technology',
        title: '2024 Tech Sector Outlook: AI Integration in MENA',
        summary: 'We expect AI adoption to move from narrative to procurement cycles, with banks and telcos leading the first wave of spend.',
        readTime: '6 min',
      },
      {
        category: 'FINTECH',
        country: 'UAE',
        date: '04 May 2024',
        sector: 'Digital Banking',
        title: 'Payments rails are becoming the new battleground',
        summary: 'Wallet usage is scaling, but the winner set will be defined by distribution, not just product breadth.',
        readTime: '5 min',
      },
      {
        category: 'SOFTWARE',
        country: 'Egypt',
        date: '22 Apr 2024',
        sector: 'Software',
        title: 'Recurring revenue is finally showing up in listed software',
        summary: 'Subscription revenue and implementation services are stabilizing margins across the small-cap tech universe.',
        readTime: '4 min',
      },
      {
        category: 'INFRA',
        country: 'Qatar',
        date: '08 Apr 2024',
        sector: 'Infrastructure',
        title: 'Cloud capacity is now a core utility input',
        summary: 'Data center build-outs are starting to influence power demand, connectivity spend, and capex discipline.',
        readTime: '5 min',
      },
    ],
  },
  'leila-hassan': {
    name: 'Leila Hassan',
    title: 'Lead, Fintech & Payments',
    desk: 'Financial Services Research',
    location: 'Cairo',
    badge: 'Client Favorite',
    email: 'leila.hassan@efghermes.com',
    phone: '+20 2 2234 7788',
    bio: 'Leila tracks banking, payments, and consumer finance with a focus on deposit behavior, digital acquisition, and product monetization.',
    focus: ['Payments', 'Consumer Finance', 'Banking', 'Deposit Trends'],
    stats: [
      { label: 'Reports published', value: '118' },
      { label: 'Covered names', value: '22' },
      { label: 'Markets tracked', value: '5' },
      { label: 'Last published', value: '15 May 2024' },
    ],
    reports: [
      {
        category: 'FINANCE',
        country: 'Saudi Arabia',
        date: '15 May 2024',
        sector: 'Payments',
        title: 'Emerging Blockchain Trends in Middle Eastern Markets',
        summary: 'Tokenized settlement is still early, but the operating leverage from modernized rails is already visible.',
        readTime: '5 min',
      },
      {
        category: 'BANKS',
        country: 'Egypt',
        date: '09 May 2024',
        sector: 'Financials',
        title: 'Deposit pricing is the new edge in retail banking',
        summary: 'The banks with the strongest franchises are no longer winning on price alone, but on product stickiness.',
        readTime: '6 min',
      },
      {
        category: 'FINTECH',
        country: 'UAE',
        date: '25 Apr 2024',
        sector: 'Fintech',
        title: 'Wallet wars: distribution beats feature lists',
        summary: 'Consumer adoption is rewarding names that can embed payments into broader daily-use ecosystems.',
        readTime: '4 min',
      },
      {
        category: 'CREDIT',
        country: 'Kuwait',
        date: '11 Apr 2024',
        sector: 'Consumer Finance',
        title: 'Credit underwriting is tightening at the margin',
        summary: 'Portfolio quality remains sound, but pricing discipline matters more as growth normalizes.',
        readTime: '4 min',
      },
    ],
  },
  'omar-al-mansoori': {
    name: 'Omar Al-Mansoori',
    title: 'Senior Analyst, Financials',
    desk: 'Banks & Consumer Finance',
    location: 'Dubai',
    badge: 'Top Conviction',
    email: 'omar.al-mansoori@efghermes.com',
    phone: '+971 4 555 0192',
    bio: 'Omar covers regional banks and consumer finance names, with a particular focus on earnings power, funding mix, and rate sensitivity.',
    focus: ['Banks', 'Consumer Finance', 'Rates', 'Earnings'],
    stats: [
      { label: 'Reports published', value: '156' },
      { label: 'Covered names', value: '31' },
      { label: 'Markets tracked', value: '7' },
      { label: 'Last published', value: '18 May 2024' },
    ],
    reports: [
      {
        category: 'FINANCE',
        country: 'Saudi Arabia',
        date: '15 May 2024',
        sector: 'Banks',
        title: 'Impact of AI on Global Stock Exchanges',
        summary: 'The real story is not automation, but the marginal improvement in client workflows and risk analytics.',
        readTime: '5 min',
      },
      {
        category: 'BANKS',
        country: 'Kuwait',
        date: '10 May 2024',
        sector: 'Financials',
        title: 'Funding discipline is now the main moat',
        summary: 'We favor institutions with sticky deposits and a clear path to earnings resilience through the cycle.',
        readTime: '6 min',
      },
      {
        category: 'CREDIT',
        country: 'UAE',
        date: '02 May 2024',
        sector: 'Lending',
        title: 'Consumer loan growth is normalizing from a high base',
        summary: 'The next leg will be driven by cross-sell and fee income rather than pure balance-sheet expansion.',
        readTime: '4 min',
      },
      {
        category: 'STRATEGY',
        country: 'Egypt',
        date: '18 Apr 2024',
        sector: 'Financials',
        title: 'Selective exposure still wins in a rate-cut regime',
        summary: 'As rates move lower, the market will reward balance-sheet quality and operating leverage.',
        readTime: '5 min',
      },
    ],
  },
  'jihane-benmansour': {
    name: 'Jihane Benmansour',
    title: 'Head of Real Estate Research',
    desk: 'Property, REITs, Construction',
    location: 'Casablanca',
    badge: 'Top Rated Analyst 2024',
    email: 'jihane.benmansour@efghermes.com',
    phone: '+212 5 1234 8890',
    bio: 'Jihane covers property developers, construction demand, and the capital allocation cycle across the regional real estate universe.',
    focus: ['Real Estate', 'Construction', 'REITs', 'Capital Cycle'],
    stats: [
      { label: 'Reports published', value: '104' },
      { label: 'Covered names', value: '19' },
      { label: 'Markets tracked', value: '5' },
      { label: 'Last published', value: '18 May 2024' },
    ],
    reports: [
      {
        category: 'REAL ESTATE',
        country: 'Saudi Arabia',
        date: '18 May 2024',
        sector: 'Property',
        title: 'Real estate: late cycle, but not the cycle you think',
        summary: 'Supply is back, prices are cooling, and yet velocity is holding up. The mix is rotating toward income.',
        readTime: '7 min',
      },
      {
        category: 'DEVELOPERS',
        country: 'UAE',
        date: '11 May 2024',
        sector: 'Property',
        title: 'Residential demand is broadening beyond prime assets',
        summary: 'Affordability constraints are reshaping demand into the mid-income tier, where the take-up remains resilient.',
        readTime: '5 min',
      },
      {
        category: 'CONSTRUCTION',
        country: 'Egypt',
        date: '03 May 2024',
        sector: 'Materials',
        title: 'Order books are stabilizing in building materials',
        summary: 'The capex pipeline remains healthy, but the winners are now names with balance-sheet flexibility.',
        readTime: '4 min',
      },
      {
        category: 'REIT',
        country: 'Qatar',
        date: '22 Apr 2024',
        sector: 'REITs',
        title: 'Yield compression is slowing, not reversing',
        summary: 'We still see room for income-led returns, but valuation discipline matters more than beta exposure.',
        readTime: '4 min',
      },
    ],
  },
  'layla-hassan': {
    name: 'Layla Hassan',
    title: 'Energy & Utilities Analyst',
    desk: 'Power, Utilities, Renewables',
    location: 'Riyadh',
    badge: 'Sector Specialist',
    email: 'layla.hassan@efghermes.com',
    phone: '+966 11 555 4401',
    bio: 'Layla tracks utilities, renewable build-outs, and industrial power demand with an emphasis on infrastructure execution and cash flow visibility.',
    focus: ['Energy', 'Utilities', 'Renewables', 'Industrial Power'],
    stats: [
      { label: 'Reports published', value: '97' },
      { label: 'Covered names', value: '16' },
      { label: 'Markets tracked', value: '4' },
      { label: 'Last published', value: '18 May 2024' },
    ],
    reports: [
      {
        category: 'ENERGY',
        country: 'Egypt',
        date: '18 May 2024',
        sector: 'Renewables',
        title: 'Renewable energy infrastructure scales rapidly',
        summary: 'Solar and wind projects are seeing massive investment, improving energy security and lowering fuel dependence.',
        readTime: '5 min',
      },
      {
        category: 'UTILITIES',
        country: 'UAE',
        date: '14 May 2024',
        sector: 'Power',
        title: 'Utility balance sheets are absorbing the grid upgrade cycle',
        summary: 'Capital intensity is rising, but regulated returns continue to support the multi-year build-out.',
        readTime: '6 min',
      },
      {
        category: 'ENERGY',
        country: 'Saudi Arabia',
        date: '06 May 2024',
        sector: 'Oil & Gas',
        title: 'Industrial power demand remains the quiet compounding story',
        summary: 'Data centers, desalination, and manufacturing are all pulling from the same expanding load base.',
        readTime: '4 min',
      },
      {
        category: 'UTILITIES',
        country: 'Qatar',
        date: '28 Apr 2024',
        sector: 'Utilities',
        title: 'The grid is becoming the bottleneck, not generation',
        summary: 'Transmission and storage are the constraining variables as load growth accelerates.',
        readTime: '5 min',
      },
    ],
  },
  'mourad-moray': {
    name: 'Mourad Moray',
    title: 'Head of Financials Research',
    desk: 'Banks & Insurance',
    location: 'Cairo',
    badge: 'Coverage Lead',
    email: 'mourad.moray@efghermes.com',
    phone: '+20 2 9988 2233',
    bio: 'Mourad covers the banks and financial institutions universe with a focus on capital return, asset quality, and earnings durability.',
    focus: ['Banks', 'Insurance', 'Capital Return', 'Risk'],
    stats: [
      { label: 'Reports published', value: '181' },
      { label: 'Covered names', value: '34' },
      { label: 'Markets tracked', value: '6' },
      { label: 'Last published', value: '17 Apr 2026' },
    ],
    reports: [
      {
        category: 'Earnings',
        country: 'Egypt',
        date: '17 Apr 2026',
        sector: 'Banks',
        title: 'Q1 2026 Results Review: Strong Q1',
        summary: 'Outperformance was driven by higher net interest income and lower provisions, with costs remaining contained.',
        readTime: '5 min',
      },
      {
        category: 'Update',
        country: 'Egypt',
        date: '12 Mar 2026',
        sector: 'Banks',
        title: 'Sector Note: Egyptian Banks Mid-Cycle',
        summary: 'CIB and peers remain well-positioned for rate normalization and moderate loan growth.',
        readTime: '6 min',
      },
      {
        category: 'Initiation',
        country: 'Egypt',
        date: '15 Jan 2026',
        sector: 'Banks',
        title: 'Best-in-class franchise with superior earnings power',
        summary: 'We like the combination of market share, fee income, and a strong capital cushion.',
        readTime: '7 min',
      },
      {
        category: 'Flash Note',
        country: 'Egypt',
        date: '08 Feb 2026',
        sector: 'Banks',
        title: 'Q4 2025 Quick Take: Solid Q4',
        summary: 'Strong NII growth kept margins elevated while provisioning remained benign.',
        readTime: '4 min',
      },
    ],
  },
  'yasser-fawzy': {
    name: 'Yasser Fawzy',
    title: 'Analyst, Banks Coverage',
    desk: 'Egypt Financials',
    location: 'Cairo',
    badge: 'On-the-Ground Coverage',
    email: 'yasser.fawzy@efghermes.com',
    phone: '+20 2 9911 6677',
    bio: 'Yasser covers operating trends, digital banking, and funding dynamics across the Egyptian financials universe.',
    focus: ['Digital Banking', 'Funding', 'Earnings', 'Consumer Credit'],
    stats: [
      { label: 'Reports published', value: '93' },
      { label: 'Covered names', value: '17' },
      { label: 'Markets tracked', value: '3' },
      { label: 'Last published', value: '20 Dec 2025' },
    ],
    reports: [
      {
        category: 'Update',
        country: 'Egypt',
        date: '20 Dec 2025',
        sector: 'Banks',
        title: 'Digital Banking: The New Frontier',
        summary: 'Mobile adoption is accelerating as banks invest in acquisition, retention, and self-service capabilities.',
        readTime: '5 min',
      },
      {
        category: 'Flash Note',
        country: 'Egypt',
        date: '08 Feb 2026',
        sector: 'Banks',
        title: 'Q4 2025 Quick Take: Strong balance sheet quality',
        summary: 'Fee income and a stable funding base continue to offset margin pressure from the rate cycle.',
        readTime: '4 min',
      },
      {
        category: 'Macro',
        country: 'Egypt',
        date: '03 Dec 2025',
        sector: 'Macro',
        title: 'Liquidity conditions are improving at the margin',
        summary: 'As the system normalizes, we expect loan growth to remain selective rather than broad based.',
        readTime: '4 min',
      },
      {
        category: 'Update',
        country: 'Egypt',
        date: '20 Nov 2025',
        sector: 'Banks',
        title: 'Client acquisition is shifting to digital-first channels',
        summary: 'The challenge is no longer reach, but unit economics and cross-sell conversion.',
        readTime: '5 min',
      },
    ],
  },
  'rawan-oueidat': {
    name: 'Rawan Oueidat',
    title: 'Lead, KSA Equities',
    desk: 'Saudi Arabia Strategy',
    location: 'Riyadh',
    badge: 'Market Favorite',
    email: 'rawan.oueidat@efghermes.com',
    phone: '+966 11 555 7220',
    bio: 'Rawan follows Saudi macro and equity flows with emphasis on the private-sector multiplier, capex, and earnings breadth.',
    focus: ['KSA Equities', 'Macro', 'Flows', 'Private Sector'],
    stats: [
      { label: 'Reports published', value: '126' },
      { label: 'Covered names', value: '25' },
      { label: 'Markets tracked', value: '4' },
      { label: 'Last published', value: '17 Apr 2026' },
    ],
    reports: [
      {
        category: 'Equity',
        country: 'Saudi Arabia',
        date: '17 Apr 2026',
        sector: 'Strategy',
        title: 'Giga-projects and the private sector multiplier',
        summary: 'PIF capex is the headline, but the second-order effects on logistics and industrials are the real trade.',
        readTime: '6 min',
      },
      {
        category: 'Macro',
        country: 'Saudi Arabia',
        date: '02 Apr 2026',
        sector: 'Macro',
        title: 'Domestic demand remains the key offset to softer oil beta',
        summary: 'Consumption and capex are doing the heavy lifting as the market recalibrates to a broader earnings base.',
        readTime: '5 min',
      },
      {
        category: 'Strategy',
        country: 'Saudi Arabia',
        date: '12 Mar 2026',
        sector: 'Strategy',
        title: 'Breadth matters more than headline index direction',
        summary: 'We continue to prefer companies with leverage to domestic demand and project execution.',
        readTime: '4 min',
      },
      {
        category: 'Update',
        country: 'Saudi Arabia',
        date: '20 Feb 2026',
        sector: 'Market Flows',
        title: 'Foreign participation is stabilizing at higher levels',
        summary: 'Turnover is improving as international flows return and domestic institutions stay constructive.',
        readTime: '4 min',
      },
    ],
  },
  'mohamed-abu-basha': {
    name: 'Mohamed Abu Basha',
    title: 'Head of Macro Research',
    desk: 'Macro, Rates, FX',
    location: 'Cairo',
    badge: 'Macro Lead',
    email: 'mohamed.abu-basha@efghermes.com',
    phone: '+20 2 9988 1100',
    bio: 'Mohamed covers macro, rates, and FX across MENA with a focus on policy transmission and the earnings implications of regime shifts.',
    focus: ['Macro', 'Rates', 'FX', 'Policy'],
    stats: [
      { label: 'Reports published', value: '173' },
      { label: 'Covered markets', value: '8' },
      { label: 'Models updated', value: '39' },
      { label: 'Last published', value: '17 Apr 2026' },
    ],
    reports: [
      {
        category: 'Macro',
        country: 'Egypt',
        date: '17 Apr 2026',
        sector: 'FX',
        title: 'FX normalization: what sticks after the float',
        summary: 'Eighteen months in, the real economy is still metabolizing the exchange regime shift.',
        readTime: '7 min',
      },
      {
        category: 'Rates',
        country: 'Egypt',
        date: '04 Apr 2026',
        sector: 'Rates',
        title: 'Policy easing should remain gradual, not aggressive',
        summary: 'Inflation has eased, but the central bank will likely keep the path cautious to preserve credibility.',
        readTime: '5 min',
      },
      {
        category: 'Macro',
        country: 'Saudi Arabia',
        date: '19 Mar 2026',
        sector: 'Macro',
        title: 'Oil beta is less dominant than the market assumes',
        summary: 'Domestic demand, investment intensity, and policy execution are now bigger drivers of earnings dispersion.',
        readTime: '5 min',
      },
      {
        category: 'FX',
        country: 'Morocco',
        date: '08 Mar 2026',
        sector: 'FX',
        title: 'Currency flexibility is improving trade competitiveness',
        summary: 'The policy regime is tilting toward more resilience and less one-way positioning.',
        readTime: '4 min',
      },
    ],
  },
  'ali-khalpey': {
    name: 'Ali Khalpey',
    title: 'Lead, GCC Real Assets',
    desk: 'Real Estate & Construction',
    location: 'Abu Dhabi',
    badge: 'Regional Coverage',
    email: 'ali.khalpey@efghermes.com',
    phone: '+971 2 440 7788',
    bio: 'Ali covers real assets, property, and construction demand with a focus on occupancy trends, pricing power, and supply cycles.',
    focus: ['Real Estate', 'Construction', 'GCC', 'Pricing'],
    stats: [
      { label: 'Reports published', value: '88' },
      { label: 'Covered names', value: '16' },
      { label: 'Markets tracked', value: '5' },
      { label: 'Last published', value: '16 Apr 2026' },
    ],
    reports: [
      {
        category: 'Equity',
        country: 'UAE',
        date: '16 Apr 2026',
        sector: 'Real Estate',
        title: 'Real estate: late cycle, but not the cycle you think',
        summary: 'The demand mix is rotating from speculative inventory toward income-led assets.',
        readTime: '6 min',
      },
      {
        category: 'Property',
        country: 'UAE',
        date: '02 Apr 2026',
        sector: 'Construction',
        title: 'Project delivery is now the key differentiator',
        summary: 'Balance-sheet strength matters more as the market transitions from growth to execution.',
        readTime: '5 min',
      },
      {
        category: 'REIT',
        country: 'Qatar',
        date: '19 Mar 2026',
        sector: 'REITs',
        title: 'Income yield remains the main anchor for valuations',
        summary: 'Compression may slow, but quality income still screens best in the current regime.',
        readTime: '4 min',
      },
      {
        category: 'Update',
        country: 'Saudi Arabia',
        date: '05 Mar 2026',
        sector: 'Property',
        title: 'Occupancy is holding despite higher supply',
        summary: 'The market is absorbing new delivery better than feared, especially in prime sub-sectors.',
        readTime: '5 min',
      },
    ],
  },
  'elena-sanchez-cabezudo': {
    name: 'Elena Sanchez-Cabezudo',
    title: 'Head of Banks Research',
    desk: 'GCC Banks',
    location: 'Dubai',
    badge: 'Top Conviction',
    email: 'elena.sanchez-cabezudo@efghermes.com',
    phone: '+971 4 880 1144',
    bio: 'Elena covers banks across the GCC with a focus on deposit franchise strength, digital acquisition, and earnings quality.',
    focus: ['Banks', 'Deposit Franchise', 'GCC', 'Earnings Quality'],
    stats: [
      { label: 'Reports published', value: '149' },
      { label: 'Covered names', value: '29' },
      { label: 'Markets tracked', value: '6' },
      { label: 'Last published', value: '15 Apr 2026' },
    ],
    reports: [
      {
        category: 'Equity',
        country: 'GCC',
        date: '15 Apr 2026',
        sector: 'Banks',
        title: 'Banks: deposit beta and the end of easy NIMs',
        summary: 'Repricing is done on the asset side; the next fight is funding and deposit retention.',
        readTime: '7 min',
      },
      {
        category: 'Update',
        country: 'UAE',
        date: '01 Apr 2026',
        sector: 'Banks',
        title: 'Capital return remains a key support for valuation',
        summary: 'Buybacks and dividends are still doing meaningful work in total-return stories.',
        readTime: '5 min',
      },
      {
        category: 'Strategy',
        country: 'Saudi Arabia',
        date: '20 Mar 2026',
        sector: 'Banks',
        title: 'Selective exposure still wins in a rate-cut regime',
        summary: 'We prefer institutions with sticky corporate deposits and lower operating risk.',
        readTime: '5 min',
      },
      {
        category: 'Update',
        country: 'Kuwait',
        date: '07 Mar 2026',
        sector: 'Banks',
        title: 'Funding costs are stabilizing, but the pace matters',
        summary: 'Earnings durability will hinge on franchise quality and disciplined loan growth.',
        readTime: '4 min',
      },
    ],
  },
  'ayub-ansari': {
    name: 'Ayub Ansari',
    title: 'Frontier Markets Lead',
    desk: 'Strategy & Cross-Asset',
    location: 'Karachi',
    badge: 'Frontier Specialist',
    email: 'ayub.ansari@efghermes.com',
    phone: '+92 21 4455 8899',
    bio: 'Ayub focuses on frontier equity selection, policy frameworks, and the earnings cycle across the Pakistan and North Africa universe.',
    focus: ['Frontier', 'Strategy', 'Policy', 'Cross-Asset'],
    stats: [
      { label: 'Reports published', value: '88' },
      { label: 'Covered names', value: '14' },
      { label: 'Markets tracked', value: '4' },
      { label: 'Last published', value: '16 Apr 2026' },
    ],
    reports: [
      {
        category: 'Strategy',
        country: 'Pakistan',
        date: '16 Apr 2026',
        sector: 'Frontier',
        title: 'Frontier re-rating: banks, cement, fertilizer',
        summary: 'IMF discipline plus political durability is a rare combination. We take the over on earnings growth.',
        readTime: '6 min',
      },
      {
        category: 'Macro',
        country: 'Pakistan',
        date: '01 Apr 2026',
        sector: 'Macro',
        title: 'Macro stability is finally translating into equity breadth',
        summary: 'The earnings recovery is broadening beyond the obvious cyclical beneficiaries.',
        readTime: '5 min',
      },
      {
        category: 'Update',
        country: 'Morocco',
        date: '18 Mar 2026',
        sector: 'Strategy',
        title: 'North Africa remains a selective alpha market',
        summary: 'We continue to favor names with domestic pricing power and predictable cash generation.',
        readTime: '4 min',
      },
      {
        category: 'Research',
        country: 'Egypt',
        date: '05 Mar 2026',
        sector: 'Cross-Asset',
        title: 'The market is discounting too little reform follow-through',
        summary: 'Valuations still imply a slower policy path than the base case we are using.',
        readTime: '5 min',
      },
    ],
  },
};

function fallbackReports(name: string): AnalystReport[] {
  return [
    {
      category: 'Research',
      country: 'MENA',
      date: '18 May 2024',
      sector: 'General',
      title: `${name}: latest sector read-through`,
      summary: 'A focused read on fundamentals, positioning, and what changed in the last update cycle.',
      readTime: '5 min',
    },
    {
      category: 'Update',
      country: 'MENA',
      date: '09 May 2024',
      sector: 'General',
      title: `${name}: key valuation implications`,
      summary: 'The market is re-rating the names with the cleanest earnings visibility and strongest balance sheets.',
      readTime: '4 min',
    },
    {
      category: 'Note',
      country: 'MENA',
      date: '28 Apr 2024',
      sector: 'General',
      title: `${name}: what to watch next`,
      summary: 'The next catalyst set is likely to come from earnings revisions and management commentary.',
      readTime: '3 min',
    },
    {
      category: 'Flash',
      country: 'MENA',
      date: '12 Apr 2024',
      sector: 'General',
      title: `${name}: quick take on recent flows`,
      summary: 'Positioning is still mixed, but the best names are seeing more persistent buying interest.',
      readTime: '3 min',
    },
  ];
}

function fallbackProfile(slug = ''): AnalystProfile {
  const displayName = titleFromSlug(slug) || 'Analyst';
  return {
    name: displayName,
    title: 'Research Analyst',
    desk: 'Institutional Research',
    location: 'MENA',
    badge: 'Research Desk',
    email: `${slug || 'analyst'}@efghermes.com`,
    phone: '+20 2 0000 0000',
    bio: `${displayName} covers a broad research universe with a focus on fundamentals, earnings, and market catalysts.`,
    focus: ['Research', 'Markets', 'Earnings', 'Strategy'],
    stats: [
      { label: 'Reports published', value: '64' },
      { label: 'Covered names', value: '12' },
      { label: 'Markets tracked', value: '4' },
      { label: 'Last published', value: '18 May 2024' },
    ],
    reports: fallbackReports(displayName),
  };
}

export function getAnalystBySlug(slug = '') {
  return DIRECTORY[slug] || fallbackProfile(slug);
}

export function analystPathFor(name = '') {
  const slug = slugifyAnalystName(name) || 'analyst';
  return `/analyst/${slug}`;
}
